sudo: required

language: ruby

services:
  - docker

script:
- chmod 777 $HOME/android
- docker run --rm --privileged -v "$HOME/android":/home/lineageos -e GIT_USER_NAME=jfloff -e GIT_USER_EMAIL=jfloff@inesc-id.pt -e DEVICE_CODENAME=klte -ti jfloff/lineageos lineageos init build

cache:
  directories:
  - $HOME/android
