version: 2
jobs:
  build:
    docker:
      - image: jfloff/lineageos 
        environment:
          GIT_USER_NAME: jfloff
          GIT_USER_EMAIL: jfloff@inesc-id.pt
          DEVICE_CODENAME: klte 
        command: lineageos init build 
